# Generated by Django 6.0 on 2026-01-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
