# Generated by Django 6.0.1 on 2026-01-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_historicalproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.producto')),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
            },
            bases=('gestion.producto',),
        ),
        migrations.CreateModel(
            name='Arroz',
            fields=[
            ],
            options={
                'verbose_name': '🥘 Arroz',
                'verbose_name_plural': '🥘 Arroces',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.CreateModel(
            name='Sopa',
            fields=[
            ],
            options={
                'verbose_name': '🍲 Sopa',
                'verbose_name_plural': '🍲 Sopas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Todos los Platillos', 'verbose_name_plural': '📂 Todos los Platillos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebidas'), ('arroz', 'Arroces'), ('sopa', 'Sopas'), ('extra', 'Extras'), ('otro', 'Otros')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HistoricalProducto',
        ),
    ]
