# Generated by Django 6.0.1 on 2026-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_extra_arroz_sopa_alter_mesa_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
            ],
            options={
                'verbose_name': '🍹 Bebida',
                'verbose_name_plural': '🍹 Bebidas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
            ],
            options={
                'verbose_name': '🍟 Extra',
                'verbose_name_plural': '🍟 Extras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
    ]
