# Generated by Django 6.0.1 on 2026-01-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_delete_bebida_detallepedido_nota_bebida_delete_extra_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arroz',
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Sopa',
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto Base', 'verbose_name_plural': 'Productos Base'},
        ),
    ]
