# Generated by Django 6.0.1 on 2026-01-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_pedido_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_diario',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Ticket Diario'),
        ),
    ]
