# Generated by Django 6.0.1 on 2026-01-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_pedido_numero_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Caja / Cobros',
                'verbose_name_plural': 'Caja / Cobros',
                'managed': False,
            },
        ),
    ]
