# Generated by Django 6.0.1 on 2026-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_cedula',
            field=models.CharField(default='9999999999', max_length=13),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='Consumidor Final', max_length=200),
        ),
    ]
