# Generated by Django 6.0.1 on 2026-01-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_pedido_cliente_cedula_pedido_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
