# Generated by Django 6.0.1 on 2026-01-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_remove_asistencia_hora_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='nota',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de retraso'),
        ),
    ]
