# Generated by Django 6.0.1 on 2026-01-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_asistencia_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='activa',
        ),
        migrations.AddField(
            model_name='mesa',
            name='piso',
            field=models.CharField(choices=[('Piso 1', 'Piso 1'), ('Piso 2', 'Piso 2')], default='Piso 1', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
