# Generated by Django 6.0.1 on 2026-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_remove_mesa_activa_mesa_piso_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('mesa-cuadrada', 'Cuadrada (Estándar)'), ('mesa-redonda', 'Redonda (Rústica)'), ('mesa-larga', 'Rectangular (Larga)')], default='mesa-cuadrada', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_x',
            field=models.IntegerField(default=10, help_text='Distancia desde la izquierda (0 a 90)', verbose_name='Posición X (%)'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_y',
            field=models.IntegerField(default=10, help_text='Distancia desde arriba (0 a 90)', verbose_name='Posición Y (%)'),
        ),
    ]
