# Generated by Django 6.0.1 on 2026-02-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_mesa_forma_mesa_pos_x_mesa_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Especiales / Decoración'),
        ),
        migrations.CreateModel(
            name='ReservaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota_plato', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota del Plato')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_preordenados', to='gestion.reserva')),
            ],
            options={
                'verbose_name': 'Plato Pre-ordenado',
                'verbose_name_plural': 'Pre-orden de Comida',
            },
        ),
    ]
