# Generated by Django 6.0.1 on 2026-02-01 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_reserva_notas_reservaplato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'managed': False, 'verbose_name': 'Cobros', 'verbose_name_plural': 'Cobros'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta/Caja', 'verbose_name_plural': 'Ventas/Caja'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=50),
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Cierre')),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Historial de Cajas',
            },
        ),
    ]
