# Generated by Django 6.0.1 on 2026-02-01 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_alter_caja_options_alter_venta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Descripción del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Proveedores', 'Proveedores / Insumos'), ('Servicios', 'Servicios Básicos (Luz/Agua)'), ('Personal', 'Pagos a Personal'), ('Mantenimiento', 'Mantenimiento / Reparaciones'), ('Otro', 'Otros Gastos')], default='Otro', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/', verbose_name='Foto/Recibo (Opcional)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
            },
        ),
    ]
