# Generated by Django 6.0.1 on 2026-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveIntegerField(default=2, verbose_name='N° Personas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ej: 0991234567', max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
