# Generated by Django 6.0.1 on 2026-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_reserva_numero_personas_reserva_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
