# Generated by Django 6.0.1 on 2026-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_pedido_comprobante_pago_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('Listo', 'Listo'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Pendiente', '---'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_diario',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='ID'),
        ),
    ]
