"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g3(&&_ur#s%kkbltf$j5dsonl6a-7o^1vp+%buq79zj-#-2^&c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['straight-rowena-universidadchimborazo-7d598f7d.koyeb.app', 'localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
    'menu',
    'core',
    'django_cleanup.apps.CleanupConfig',
    'simple_history',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://koyeb-adm:npg_6vs2jXMIpLPz@ep-restless-sun-ai3kxmwq.us-east-1.aws.neon.tech/koyebdb?sslmode=require&options=endpoint%3Dep-restless-sun-ai3kxmwq'
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec' 

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


JAZZMIN_SETTINGS = {
    # Títulos y Marca
    "site_title": "FoodManage Admin",
    "site_header": "Máncora Marisquería",
    "site_brand": "Máncora Marisquería",
    "welcome_sign": "Bienvenido al Sistema de Gestión FoodManage",
    "copyright": "Mancora Marísqueria-FoodManage",
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_actions.js",

    # Logos
    "site_logo": "logo_mancora.PNG", 
    "login_logo": "logo_mancora.PNG",
    "login_logo_dark": "logo_mancora.PNG",
    "site_logo_classes": "img-circle",

    # Interfaz
    "show_sidebar": True,
    "navigation_expanded": False, 
    "search_model": ["gestion.Producto"],

    "hide_models": ["gestion.Producto"],
    
    # 1. Enlaces Superiores (Solo Inicio)
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Página Web", "url": "/", "new_window": True, "icon": "fas fa-globe-americas"},
    ],

    # 2. Menú Lateral Personalizado
    # CORRECCIÓN: Se eliminaron los permisos para que el botón sea visible para JOSTIN
    "custom_links": {
        "gestion": [ 
            {
                "name": "Tomar Pedido", 
                "url": "tomar_pedido", 
                "icon": "fas fa-cash-register", 
                "permissions": []  # <--- ESTO VACÍO HACE QUE APAREZCA SIEMPRE
            },

            {
                "name": "Cocina", 
                "url": "/admin/gestion/cocina/",  # Nombre de la URL en urls.py
                "icon": "fas fa-utensils", 
                "permissions": [] 
            },
        ],
    },

"icons": {
    "auth": "fas fa-users-cog",
    "auth.user": "fas fa-user",
    "auth.Group": "fas fa-users",
    
    # GESTIÓN (Se queda igual)
    "gestion.Pedido": "fas fa-list-alt",
    "gestion.Venta": "fas fa-cash-register",
    "gestion.Mesa": "fas fa-chair",
    "gestion.Reserva": "fas fa-calendar-alt",
    "gestion.Asistencia": "fas fa-user-clock",
    "gestion.TomarPedido": "fas fa-concierge-bell",
    "gestion.Cocina": "fas fa-fire",
    "gestion.Caja": "fas fa-money-bill-wave",
    "gestion.Gasto": "fas fa-hand-holding-usd",

    "menu.Catalogo": "fas fa-book-open",
        "menu.Bebida": "fas fa-wine-glass-alt",
        "menu.Arroz": "fas fa-utensils",        
        "menu.Sopa": "fas fa-mug-hot", 
        "menu.Porcion": "fas fa-drumstick-bite",          
        "menu.Extra": "fas fa-bacon",
},

# Orden del menú lateral (USUARIOS PRIMERO)
    "order_with_respect_to": [
        # 1. USUARIOS Y SEGURIDAD (Primero)
        "auth",            # Esto pone "Autenticación y autorización" arriba
        "auth.user",
        "auth.Group",

        # 2. GESTIÓN (Segundo)
        "gestion",
        "gestion.Pedido",
        "gestion.Caja",
        "gestion.Gasto",
        "gestion.Cocina",
        "gestion.TomarPedido",
        "gestion.Pedido",
        "gestion.Venta",
        "gestion.Mesa",
        "gestion.Reserva",
        "gestion.Asistencia",
        
        # 3. MENÚ (Tercero)
        "menu",
        "menu.Catalogo",
        "menu.Bebida",
        "menu.Arroz",
        "menu.Sopa",
        "menu.Extra",
    ],

    # Estilos
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

# Configuración de UI para colores neón y comportamiento táctil
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-lime", # Resalta el botón de pedidos y selecciones en verde neón
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-lime", # Menú lateral oscuro con detalles verde lima
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly", # Mantiene el estilo elegante y oscuro
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Esta es la línea que te falta y causó el error
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuración de archivos multimedia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redirección tras el Login
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/'

# Configuración de Sesiones Persistentes
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Evita que la sesión se borre al cerrar el navegador
SESSION_COOKIE_AGE = 1209600             # La sesión durará 2 semanas (en segundos)
SESSION_SAVE_EVERY_REQUEST = True        # Actualiza la duración en cada clic

# =========================================================
# CONFIGURACIÓN DE CORREO (GMAIL)
# =========================================================

# Usamos el servicio SMTP de Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Tu correo real
EMAIL_HOST_USER = 'mancoramarisqueria2026@gmail.com'

# AQUÍ PEGAS LA CLAVE DE 16 LETRAS QUE OBTUVISTE EN EL PASO 1
# (Ponla dentro de las comillas)
EMAIL_HOST_PASSWORD = 'nhkh lkbo knqt ekqg'

# Configuración del remitente
DEFAULT_FROM_EMAIL = 'Soporte Máncora <mancoramarisqueria2026@gmail.com>'