# Generated by Django 6.0.1 on 2026-01-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0012_delete_arroz_delete_bebida_delete_extra_delete_sopa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arroz',
            fields=[
            ],
            options={
                'verbose_name': '🥘 Arroces',
                'verbose_name_plural': '🥘 Arroces',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
            ],
            options={
                'verbose_name': '🍹 Bebidas',
                'verbose_name_plural': '🍹 Bebidas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
            ],
            options={
                'verbose_name': '📂 Ver Menú Completo',
                'verbose_name_plural': '📂 Ver Menú Completo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
            ],
            options={
                'verbose_name': '🍟 Extras',
                'verbose_name_plural': '🍟 Extras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
        migrations.CreateModel(
            name='Sopa',
            fields=[
            ],
            options={
                'verbose_name': '🍲 Sopas',
                'verbose_name_plural': '🍲 Sopas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
    ]
