# Generated by Django 6.0.1 on 2026-01-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arroz',
            options={'verbose_name': 'Arroces', 'verbose_name_plural': 'Arroces'},
        ),
        migrations.AlterModelOptions(
            name='bebida',
            options={'verbose_name': 'Bebidas', 'verbose_name_plural': 'Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name': 'Ver Menú Completo', 'verbose_name_plural': 'Ver Menú Completo'},
        ),
        migrations.AlterModelOptions(
            name='extra',
            options={'verbose_name': 'Extras', 'verbose_name_plural': 'Extras'},
        ),
        migrations.AlterModelOptions(
            name='sopa',
            options={'verbose_name': 'Sopas', 'verbose_name_plural': 'Sopas'},
        ),
    ]
