# Generated by Django 6.0.1 on 2026-01-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_mesa_forma_mesa_pos_x_mesa_pos_y'),
        ('menu', '0002_alter_arroz_options_alter_bebida_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcion',
            fields=[
            ],
            options={
                'verbose_name': 'Porciones',
                'verbose_name_plural': 'Porciones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.producto',),
        ),
    ]
